FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base

# Atualiza pacotes e instala ferramentas necessárias
RUN apt-get update && \
    apt-get install -y curl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Instala Node.js v22.15.0
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@latest
