services:
  despesas-frontend-angular-dev:
    container_name: dev
    image: alexfariakof/despesas-frontend-angular-dev-img
    build:
      context: .
      dockerfile: ./Dockerfile.development
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certificate/ssl_certificate.pem:/etc/nginx/certificate/ssl_certificate.pem:ro
      - ./certificate/ssl_certificate.key:/etc/nginx/certificate/ssl_certificate.key:ro
