services:
  despesas-frontend-angular-prod:
    container_name: prod
    image: alexfariakof/despesas-frontend-angular-img
    build:
      context: .
      dockerfile: ./Dockerfile.production
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certificate/ssl_certificate.pem:/etc/nginx/certificate/ssl_certificate.pem:ro
      - ./certificate/ssl_certificate.key:/etc/nginx/certificate/ssl_certificate.key:ro
