#stage 1
FROM node:current-slim as node
WORKDIR /app
COPY . .
#RUN npm install -g npm@11.5.2 >/dev/null 2
RUN npm install >/dev/null 2>&1
RUN npm run build >/dev/null 2>&1

#stage 2
FROM nginx:alpine
COPY --from=node /app/dist /usr/share/nginx/html
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
