export * from './abstractions/menu.strategy.interface';
export * from './categoria/categoria-strategy';
export * from './configuracoes/configuracoes-strategy';
export * from './despesa/despesa-strategy';
export * from './home/home.strategy';
export * from './lancamento/lancamento-strategy';
export * from './perfil/perfil-strategy';
export * from './receita/receita-strategy';
export *  from './invalid/invalid.strategy';