version: '3.9'

services:
  db:
    container_name: mysql-server-in-docker
    image: alexfariakof/mysql-server-db-img
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-restore
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: '!12345'
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: DespesasPessoaisDB
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_0900_ai_ci
    ports:
        - 3306:3306
  
  