name: Sync AngularApp

on:
  push:
    branches:
      - develop
    paths:
      - AngularApp/**

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Set commit metadata
      id: commit_info
      run: |
        echo "COMMIT_MSG<<EOF" >> $GITHUB_ENV
        git log -1 --pretty=%B >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:%an'%3C'%ae'%3E')" >> $GITHUB_ENV
        echo "COMMIT_DATE=$(git log -1 --date=iso-strict --pretty=format:%ad)" >> $GITHUB_ENV

    - name: Clone destination repo
      run: |
        git config --global user.email "alexfariakof@yahoo.com.br"
        git config --global user.name "Alex Ribeiro de Faria"

        git clone https://x-access-token:${{ secrets.TOKEN_DESTINO }}@github.com/alexribeirofaria/angular-frontend-despesas.git
        cd angular-frontend-despesas

        cp -r ../AngularApp/* .

        git add .
        git commit --author="${{ env.COMMIT_AUTHOR }}" --date="${{ env.COMMIT_DATE }}" -m "${{ env.COMMIT_MSG }}" || echo "No changes to commit"
        git push origin master
    
