name: Sync AngularApp folder to another repo

on:
  push:
    branches:
      - develop
    paths:
      - 'AngularApp/**'

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Set commit metadata
      run: |
        echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV
        echo "COMMIT_DATE=$(git log -1 --date=iso-strict --pretty=format:'%ad')" >> $GITHUB_ENV

    - name: Clone destination repo
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "GitHub Action"

        git clone https://x-access-token:${{ secrets.TOKEN_DESTINO }}@github.com/alexribeirofaria/angular-frontend-despesas.git
        cd angular-frontend-despesas

        cp -r ../AngularApp/* .

        git add .
        git commit --author="${{ env.COMMIT_AUTHOR }}" --date="${{ env.COMMIT_DATE }}" -m "${{ env.COMMIT_MSG }}" || echo "No changes to commit"
        git push origin master
    